### ISSUE TITLE
wtf.quick_form / wtf.form_field cant render FormField and DateTimeField classes

### ISSUE THREAD

**Issue by laundmo** [hfilimonescu/flask-bs4#7]
FormField renders as a completely unformatted html table of the fields
DateTimeField renders as a empty text box, when it should either render as a datepicker field that allows for manually entering the time or a datetimepicker

i may make a PR at some point for at least FormField but since i am busy right now that will have to wait

**Comment by hfilimonescu** [comment]
Hi @laundmo ,

I have fixed the `FormField` issue in the new release 4.5.0.3

Regarding the `DateTimeField` I am not going to change anything. According to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime) "[t]his feature is obsolete. Although it may still work in some browsers, its use is discouraged since it could be removed at any time. Try to avoid using it. [...] Instead, browsers are implementing (and developers are encouraged to use) `<input type="datetime-local">`.".

Cheers
